version: "3"

services:

  shopware:
    image: dockware/dev:latest
    container_name: shopware
    volumes: # First time this volumes node will commented
      - "./src:/var/www/html"
    ports:
      - "80:80"
      - "2200:22"
      - "3306:3306"
    networks:
      - web

  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    networks:
      - web
    environment:
      - "EA_JAVA_OPTS=-Xms512m -Xms512m"
      - discovery.type=single-node

  redis:
    image: redis:5.0.6
    container_name: redis
    networks:
      - web

networks:
  web:
    external: false
